# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import llm_server_pb2 as llm__server__pb2


class LLMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.generate = channel.unary_unary(
                '/LLMService/generate',
                request_serializer=llm__server__pb2.LLM_Input.SerializeToString,
                response_deserializer=llm__server__pb2.LLM_Output.FromString,
                )


class LLMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LLMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'generate': grpc.unary_unary_rpc_method_handler(
                    servicer.generate,
                    request_deserializer=llm__server__pb2.LLM_Input.FromString,
                    response_serializer=llm__server__pb2.LLM_Output.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LLMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LLMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LLMService/generate',
            llm__server__pb2.LLM_Input.SerializeToString,
            llm__server__pb2.LLM_Output.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
