# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llm_server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10llm_server.proto\"8\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08sentence\x18\x02 \x01(\t\x12\x0c\n\x04link\x18\x03 \x01(\t\"&\n\x04Link\x12\x10\n\x08position\x18\x01 \x01(\x05\x12\x0c\n\x04link\x18\x02 \x01(\t\"l\n\tLLM_Input\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x1d\n\x0c\x61nswers_list\x18\x02 \x03(\x0b\x32\x07.Answer\x12\x1b\n\x0euse_gramformer\x18\x03 \x01(\x08H\x00\x88\x01\x01\x42\x11\n\x0f_use_gramformer\"\x91\x01\n\nLLM_Output\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x12\n\ndirty_text\x18\x02 \x01(\t\x12\x18\n\tall_links\x18\x03 \x03(\x0b\x32\x05.Link\x12\x10\n\x08\x65nd_time\x18\x04 \x01(\x02\x12\x14\n\x0c\x65nd_gen_time\x18\x05 \x01(\x02\x12\x15\n\rquestion_type\x18\x06 \x01(\t23\n\nLLMService\x12%\n\x08generate\x12\n.LLM_Input\x1a\x0b.LLM_Output\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llm_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ANSWER']._serialized_start=20
  _globals['_ANSWER']._serialized_end=76
  _globals['_LINK']._serialized_start=78
  _globals['_LINK']._serialized_end=116
  _globals['_LLM_INPUT']._serialized_start=118
  _globals['_LLM_INPUT']._serialized_end=226
  _globals['_LLM_OUTPUT']._serialized_start=229
  _globals['_LLM_OUTPUT']._serialized_end=374
  _globals['_LLMSERVICE']._serialized_start=376
  _globals['_LLMSERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
